---
title: "chapter_05_part3_assignment.Rmd"
author: "Stacey Harmer"
date: "May 2, 2016"
output: html_document
---

5E3.  Write down a multiple regression to evaluate the claim: Neither amount of funding nor size
of laboratory is by itself a good predictor of time to PhD degree; but together these variables are both
positively associated with time to degree. Write down the model definition and indicate which side of
zero each slope parameter should be on

more funding = faster time and bigger lab = faster time (negative slope)

mu <- a + bf * funding + bs * lab.size
I expect both bf and bs to be negative

5E4. Suppose you have a single categorical predictor with 4 levels (unique values), labeled A, B, C
and D. Let Ai be an indicator variable that is 1 where case i is in category A. Also suppose Bi, Ci,
and Di for the other categories. Now which of the following linear models are inferentially equivalent
ways to include the categorical variable in a regression? Models are inferentially equivalent when it’s
possible to compute one posterior distribution from the posterior distribution of another model.
(1) C is the intercept
(2) not valid
(3) A is intercept
(4) no intercept assigned
(5) like 4

###### so I think 1, 3,4, 5 are equivalent

5M5. One way to reason through multiple causation hypotheses is to imagine detailed mechanisms
through which predictor variables may influence outcomes. For example, it is sometimes argued that
the price of gasoline (predictor variable) is positively associated with lower obesity rates (outcome
variable). However, there are at least two important mechanisms by which the price of gas could
reduce obesity. First, it could lead to less driving and therefore more exercise. Second, it could lead to
less driving, which leads to less eating out, which leads to less consumption of huge restaurant meals.
Can you outline one or more multiple regressions that address these two mechanisms? Assume you
can have any predictor data you need.


mean.obesity = alpha + b.p * gas.price + b.d * amt.driving

mean.obesity = alpha + b.p * gas.price + b.r * rest.meals

mean.obesity = alpha + b.p * gas.price + b.d * amt.driving + b.r * rest.meals